# https://github.com/powerline/fonts#quick-installation
---
- name: "Check powerline-fonts "
  include_role:
    name: repo_installer
  vars:
    remote_url: https://github.com/powerline/fonts.git
    src_path: "{{ powerline_font_src_path }}"

- name: "Ensure powerline-fonts output directories exists"
  file:
    path: "{{ item }}"
    state: directory
    owner: "{{ owning_user }}"
    group: "{{ owning_group }}"
  with_items:
    - "{{ local_font_cache }}"
    - "{{ local_fontconfig }}"
  when: repo_update | changed
  tags:
    - directory

- name: "Link fonts"
  file:
    path: "{{ local_font_cache }}/{{ item.path | basename }}"
    src: "{{ powerline_font_src_path }}/{{ item.path }}"
    state: link
    owner: "{{ owning_user }}"
    group: "{{ owning_group }}"
  with_filetree: "{{ powerline_font_src_path }}"
  when: repo_update | changed and item.state == "file" and item.path | regex_search("\.((o|t)tf|pcf\.gz)$")
  tags:
    - symlink
    - install

- name: Link fontconfigs
  file:
    path: "{{ config_dir }}/fontconfig/conf.d/{{ item.path | basename }}"
    src: "{{ powerline_font_src_path }}/{{ item.path }}"
    state: link
    owner: "{{ owning_user }}"
    group: "{{ owning_group }}"
  with_filetree: "{{ powerline_font_src_path }}"
  when: repo_update | changed and item.state == "file" and item.path | regex_search("\.conf$")
  tags:
    - symlink
    - install

- name: "Refresh font cache"
  command: "fc-cache -vf {{ local_font_cache }}"
  when: repo_update | changed
  tags:
    - command
    - refresh

# TODO: remove stale links
