---
- name: "Check tmux"
  include_role:
    name: repo_installer
  vars:
    remote_url: https://github.com/tmux/tmux
    src_path: "{{ tmux_src_path }}"
  notify: "rebuild tmux"

- name: "Check tpm"
  include_role:
    name: repo_installer
  vars:
    remote_url: https://github.com/tmux-plugins/tpm
    src_path: "{{ config_dir }}/tmux/plugins/tpm"
    repo_owner: "{{ owning_user }}"
    repo_group: "{{ owning_group }}"
    repo_become: no

- name: "Template tmux config"
  include_role:
    name: generic_template
  vars:
    template_root: "{{ root_dir }}"
    template_path: ".tmux.conf"
